import type { AWS } from "@serverless/typescript";

import functions from "./serverless/functions";
import dynamoResources from "./serverless/dynamoResources";
import AssetsBucketAndCloudfront from "./serverless/AssetsBucketAndCloudfront";

const serverlessConfiguration: AWS = {
  service: "duportfolioapi",
  frameworkVersion: "3",
  plugins: ["serverless-esbuild", "serverless-iam-roles-per-function"],
  provider: {
    name: "aws",
    runtime: "nodejs22.x" as never,
    region: "us-east-1",
    profile: "serverlessUser",
    iamRoleStatements: [
      {
        Effect: "Allow",
        Action: "dynamodb:*",
        Resource: [
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.portfolioTableName}",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.reelJobsTableName}",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.reelJobsTableName}/index/GSI-reel-jobs-by-template",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.reelJobsTableName}/index/GSI-reel-jobs-by-status",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.gameContextsTableName}",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.gameMediaAssetsTableName}",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.gameMediaAssetsTableName}/index/GSI-game-media-by-game",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.socialConnectionsTableName}",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.tweetActivityTableName}",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.tweetActivityTableName}/index/GSI-activity-recent",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.scheduledTweetsTableName}",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.scheduledTweetsTableName}/index/GSI-tweets-by-status",
          "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.scheduledTweetsTableName}/index/GSI-tweets-recent",
        ],
      },
      //S3
      {
        Effect: "Allow",
        Action: "s3:*",
        Resource: [
          "arn:aws:s3:::${self:custom.imageUploadBucket}",
          "arn:aws:s3:::${self:custom.imageUploadBucket}/*",
          "arn:aws:s3:::${self:custom.reelAssetsBucket}",
          "arn:aws:s3:::${self:custom.reelAssetsBucket}/*",
          "arn:aws:s3:::${self:custom.gameMediaBucket}",
          "arn:aws:s3:::${self:custom.gameMediaBucket}/*",
          "arn:aws:s3:::${self:custom.tweetMediaBucket}",
          "arn:aws:s3:::${self:custom.tweetMediaBucket}/*",
        ],
      },
      {
        Effect: "Allow",
        Action: ["ssm:GetParameter"],
        Resource: [
          "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter${self:custom.elevenLabsApiKeyParameterName}",
          "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter${self:custom.openAiApiKeyParameterName}",
          "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter${self:custom.metaAppIdParameterName}",
          "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter${self:custom.metaAppSecretParameterName}",
          "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter${self:custom.metaOauthRedirectUriParameterName}",
          "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter${self:custom.metaPageIdParameterName}",
        ],
      },
      {
        Effect: "Allow",
        Action: ["lambda:InvokeFunction"],
        Resource:
          "arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:custom.remotionLambdaFunctionName}",
      },
    ],
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    httpApi: {
      cors: {
        allowedHeaders: ["Content-Type", "Authorization"],
        allowedMethods: ["DELETE", "GET", "POST", "PATCH", "OPTIONS"],
        allowedOrigins: [
          "https://www.dunapant.dev",
          "https://dunapant.dev",
          "http://localhost:3000",
          "http://localhost:3002",
        ],
        maxAge: 86400,
      },
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1",
      NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000",

      portfolioTable: "${self:custom.portfolioTableName}",
      imageUploadBucket: "${self:custom.imageUploadBucket}",
      reelJobsTable: "${self:custom.reelJobsTableName}",
      reelAssetsBucket: "${self:custom.reelAssetsBucket}",
      gameMediaAssetsTable: "${self:custom.gameMediaAssetsTableName}",
      gameMediaBucket: "${self:custom.gameMediaBucket}",
      reelAssetTtlDays: "${self:custom.reelAssetTtlDays}",
      gameContextsTable: "${self:custom.gameContextsTableName}",
      socialConnectionsTable: "${self:custom.socialConnectionsTableName}",
      tweetActivityTable: "${self:custom.tweetActivityTableName}",
      scheduledTweetsTable: "${self:custom.scheduledTweetsTableName}",
      tweetMediaBucket: "${self:custom.tweetMediaBucket}",
      tweetMediaTtlDays: "${self:custom.tweetMediaTtlDays}",
      TWEET_STUDIO_TIMEZONE: "${env:TWEET_STUDIO_TIMEZONE, 'America/Guayaquil'}",
      TWEET_STUDIO_DAILY_TARGET: "${env:TWEET_STUDIO_DAILY_TARGET, '2'}",
      TWEET_STUDIO_SLOTS: "${env:TWEET_STUDIO_SLOTS, '13:00,20:00'}",
      OPENAI_TWEET_MODEL: "${env:OPENAI_TWEET_MODEL, 'gpt-5.4-mini'}",
      META_APP_ID: "${env:META_APP_ID, ssm:${self:custom.metaAppIdParameterName}}",
      META_APP_SECRET: "${env:META_APP_SECRET, ssm:${self:custom.metaAppSecretParameterName}}",
      META_GRAPH_VERSION: "${env:META_GRAPH_VERSION, 'v25.0'}",
      META_OAUTH_REDIRECT_URI: "${env:META_OAUTH_REDIRECT_URI, ssm:${self:custom.metaOauthRedirectUriParameterName}}",
      META_PAGE_ID: "${env:META_PAGE_ID, ssm:${self:custom.metaPageIdParameterName}}",
      SWIPE2PLAY_REEL_MAKER_URL: "${env:SWIPE2PLAY_REEL_MAKER_URL, 'https://www.dunapant.dev/10000-offline-games/reel-maker'}",
      TWEET_STUDIO_URL: "${env:TWEET_STUDIO_URL, 'https://www.dunapant.dev/tweet-studio'}",
      YOUTUBE_CLIENT_ID: "${env:YOUTUBE_CLIENT_ID, ''}",
      YOUTUBE_CLIENT_SECRET: "${env:YOUTUBE_CLIENT_SECRET, ''}",
      YOUTUBE_OAUTH_REDIRECT_URI: "${env:YOUTUBE_OAUTH_REDIRECT_URI, ''}",
      X_CLIENT_ID: "${env:X_CLIENT_ID, ''}",
      X_CLIENT_SECRET: "${env:X_CLIENT_SECRET, ''}",
      X_OAUTH_REDIRECT_URI: "${env:X_OAUTH_REDIRECT_URI, ''}",
      ELEVENLABS_API_KEY_PARAM: "${self:custom.elevenLabsApiKeyParameterName}",
      ELEVENLABS_DEFAULT_MODEL_ID: "${env:ELEVENLABS_DEFAULT_MODEL_ID, 'eleven_multilingual_v2'}",
      ELEVENLABS_DEFAULT_OUTPUT_FORMAT: "${env:ELEVENLABS_DEFAULT_OUTPUT_FORMAT, 'mp3_44100_128'}",
      ELEVENLABS_DEFAULT_VOICE_ID: "${env:ELEVENLABS_DEFAULT_VOICE_ID, '21m00Tcm4TlvDq8ikWAM'}",
      OPENAI_API_KEY_PARAM: "${self:custom.openAiApiKeyParameterName}",
      OPENAI_DEFAULT_MODEL: "${env:OPENAI_DEFAULT_MODEL, 'gpt-5.4-mini'}",
      REMOTION_AWS_REGION: "${env:REMOTION_AWS_REGION, 'us-east-1'}",
      REMOTION_FRAMES_PER_LAMBDA: "${env:REMOTION_FRAMES_PER_LAMBDA, '30'}",
      REMOTION_LAMBDA_FUNCTION_NAME: "${env:REMOTION_LAMBDA_FUNCTION_NAME, self:custom.remotionLambdaFunctionName}",
      REMOTION_SERVE_URL: "${env:REMOTION_SERVE_URL, self:custom.remotionServeUrl}",
      REMOTION_TEMPLATE_ONE_COMPOSITION: "${env:REMOTION_TEMPLATE_ONE_COMPOSITION, 'Swipe2PlayHookGameplayTemplate'}",
      REMOTION_TEMPLATE_TWO_COMPOSITION: "${env:REMOTION_TEMPLATE_TWO_COMPOSITION, 'Swipe2PlayChallengeCountdownTemplate'}",
    },
  },
  // import the function via paths
  functions,
  resources: {
    Resources: {
      ...dynamoResources,
      ...AssetsBucketAndCloudfront,
      
    },
  },
  package: { individually: true },
  custom: {
    portfolioTableName: "${sls:stage}-portfolio-table",
    imageUploadBucket: "${sls:stage}-image-upload-bucket-du-portfolio",
    reelJobsTableName: "${sls:stage}-swipe2play-reel-jobs",
    reelAssetsBucket: "${sls:stage}-swipe2play-reel-assets-du-portfolio",
    gameMediaAssetsTableName: "${sls:stage}-swipe2play-game-media-assets",
    gameMediaBucket: "${sls:stage}-swipe2play-game-media-du-portfolio",
    reelAssetTtlDays: 7,
    gameContextsTableName: "${sls:stage}-swipe2play-game-contexts",
    tweetActivityTableName: "${sls:stage}-tweet-studio-activity",
    scheduledTweetsTableName: "${sls:stage}-tweet-studio-scheduled",
    tweetMediaBucket: "${sls:stage}-tweet-studio-media-du-portfolio",
    tweetMediaTtlDays: 15,
    elevenLabsApiKeyParameterName: "/duportfolioapi/${sls:stage}/elevenlabs/api-key",
    openAiApiKeyParameterName: "/duportfolioapi/${sls:stage}/openai/api-key",
    metaAppIdParameterName: "/duportfolioapi/${sls:stage}/meta/app-id",
    metaAppSecretParameterName: "/duportfolioapi/${sls:stage}/meta/app-secret",
    metaOauthRedirectUriParameterName: "/duportfolioapi/${sls:stage}/meta/oauth-redirect-uri",
    metaPageIdParameterName: "/duportfolioapi/${sls:stage}/meta/page-id",
    remotionLambdaFunctionName:
      "remotion-render-4-0-220-mem2048mb-disk2048mb-120sec",
    remotionServeUrl:
      "https://remotionlambda-useast1-fsl5eevwd6.s3.us-east-1.amazonaws.com/sites/swipe2play-reels/index.html",
    socialConnectionsTableName: "${sls:stage}-swipe2play-social-connections",
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ["aws-sdk"],
      target: "node22",
      define: { "require.resolve": undefined },
      platform: "node",
      concurrency: 10,
    },
  },
};

module.exports = serverlessConfiguration;
