const nullableString = { type: ["string", "null"] };
const nullableNumber = { type: ["number", "null"] };
const nullableBoolean = { type: ["boolean", "null"] };

const fields = {
  sourceAuctionId: nullableString,
  coactiveProcessNumber: nullableString,
  assetType: {
    anyOf: [
      { enum: ["house", "apartment", "land", "commercial", "farm", "warehouse", "building", "other"] },
      { type: "null" },
    ],
  },
  title: nullableString,
  description: nullableString,
  province: nullableString,
  canton: nullableString,
  city: nullableString,
  parish: nullableString,
  neighborhood: nullableString,
  address: nullableString,
  addressRaw: nullableString,
  buildingName: nullableString,
  urbanization: nullableString,
  latitude: nullableNumber,
  longitude: nullableNumber,
  landAreaM2: nullableNumber,
  constructionAreaM2: nullableNumber,
  apartmentAreaM2: nullableNumber,
  parkingAreaM2: nullableNumber,
  storageAreaM2: nullableNumber,
  bedrooms: nullableNumber,
  bathrooms: nullableNumber,
  parkingSpaces: nullableNumber,
  includesParking: nullableBoolean,
  includesStorage: nullableBoolean,
  appraisalValue: nullableNumber,
  auctionBaseValue: nullableNumber,
  baseValueDerived: { type: "boolean" },
  baseValueDerivation: nullableString,
  signalingNumber: { type: ["integer", "null"], enum: [1, 2, 3, null] },
  signalingRaw: nullableString,
  legalFramework: nullableString,
  legalArticle: nullableString,
  ownershipPercentage: nullableNumber,
  isFullOwnership: nullableBoolean,
  ownershipDescription: nullableString,
  isPropertyHorizontal: nullableBoolean,
  commonAreaAliquot: nullableNumber,
  qualificationDeadlineAt: nullableString,
  documentDeadlineAt: nullableString,
  auctionStartAt: nullableString,
  auctionEndAt: nullableString,
  auctionDate: nullableString,
  depositCashPct: nullableNumber,
  depositFinancedPct: nullableNumber,
  allowsFinancing: nullableBoolean,
  financingTerms: nullableString,
  occupancyStatus: nullableString,
  liensMentioned: nullableString,
  propertyStatus: nullableString,
  contactName: nullableString,
  contactPhone: nullableString,
  contactEmail: nullableString,
  extractionConfidence: { type: "number", minimum: 0, maximum: 1 },
  warnings: { type: "array", items: { type: "string" } },
  evidence: {
    type: "array",
    items: {
      type: "object",
      additionalProperties: false,
      properties: {
        field: { type: "string" },
        value: { type: ["string", "number", "boolean", "null"] },
        source: { type: "string", enum: ["pdf"] },
        page: { type: ["integer", "null"] },
        evidence: { type: "string" },
      },
      required: ["field", "value", "source", "page", "evidence"],
    },
  },
};

export const remateExtractionSchema = {
  type: "object",
  additionalProperties: false,
  properties: fields,
  required: Object.keys(fields),
};
