export type Swipe2PlayGameContext = {
  color?: string;
  coreMechanics?: string[];
  createdAt?: string;
  gameId: string;
  gameplaySummary?: string;
  hookAngles?: string[];
  isPublished?: boolean;
  keywords?: string[];
  leaderboardMetric?: string;
  name: string;
  notes?: string;
  obstacles?: string[];
  playerGoal?: string;
  reelPrompt?: string;
  scoring?: string;
  targetAudience?: string;
  theme?: string;
  title: string;
  updatedAt?: string;
  videoAssetPath?: string;
};

export const getGameContextsTableName = () => {
  const tableName = process.env.gameContextsTable;
  if (!tableName) throw new Error("Missing gameContextsTable env var.");
  return tableName;
};

export const defaultGameContexts: Swipe2PlayGameContext[] = [
  {
    color: "#2E5A3A",
    coreMechanics: ["drive", "avoid traffic", "survive longer", "score distance"],
    gameId: "game_truck_town",
    gameplaySummary: "A quick driving survival game where the player keeps a vehicle under control through a busy toy-like town.",
    hookAngles: ["How far can you drive without crashing?", "This tiny road gets chaotic fast."],
    isPublished: true,
    keywords: ["driving", "traffic", "cars", "reaction", "survival"],
    leaderboardMetric: "distance / best run",
    name: "truck_town",
    obstacles: ["traffic", "road hazards", "tight routes"],
    playerGoal: "Drive as far as possible while avoiding crashes.",
    reelPrompt: "Fast car dodges, close calls, and a best-distance challenge.",
    scoring: "Longer clean runs push the leaderboard score higher.",
    targetAudience: "mobile arcade and driving game players",
    theme: "arcade driving",
    title: "Truck Town",
    videoAssetPath: "src/assets/videos/truck-town.mp4",
  },
  {
    color: "#7EC8E3",
    coreMechanics: ["drag to dodge", "avoid paper obstacles", "survive waves"],
    gameId: "game_finger_dodge",
    gameplaySummary: "A notebook-style survival game where the player dodges incoming pencil and paper hazards.",
    hookAngles: ["Your finger is not safe here.", "This pencil survival run gets stressful fast."],
    isPublished: true,
    keywords: ["pencil", "paper", "dodge", "school", "survival"],
    leaderboardMetric: "survival time / best score",
    name: "finger_dodge",
    obstacles: ["paper crashes", "notebook hazards", "fast obstacles"],
    playerGoal: "Survive as long as possible by dodging every obstacle.",
    reelPrompt: "Notebook visuals, quick dodges, near misses, and a survival challenge.",
    scoring: "Survival time and new records define the leaderboard.",
    targetAudience: "hypercasual mobile players",
    theme: "notebook survival",
    title: "Pencil Survival",
    videoAssetPath: "src/assets/videos/pencil-survival.mp4",
  },
  {
    color: "#5B8EC9",
    coreMechanics: ["protect balloon", "clear obstacles", "rise upward"],
    gameId: "game_rise_up",
    gameplaySummary: "A vertical rising challenge where the player protects a balloon from hazards.",
    hookAngles: ["Can you keep the balloon alive?", "One tiny hit ends the run."],
    isPublished: false,
    keywords: ["balloon", "rise", "protect", "vertical", "reflex"],
    leaderboardMetric: "height / best run",
    name: "rise_up",
    obstacles: ["falling hazards", "tight paths", "balloon pops"],
    playerGoal: "Protect the balloon and climb as high as possible.",
    reelPrompt: "Show a tense upward climb with close saves.",
    scoring: "Higher climbs create better leaderboard scores.",
    targetAudience: "casual reflex game players",
    theme: "vertical balloon challenge",
    title: "Rise Up",
  },
  {
    color: "#0A1628",
    coreMechanics: ["hit puck", "defend goal", "score first", "react fast"],
    gameId: "game_air_hockey",
    gameplaySummary: "A fast 3D air hockey match focused on reflexes, defense, and quick goals.",
    hookAngles: ["Can you win this air hockey rally?", "Defense matters more than you think."],
    isPublished: true,
    keywords: ["air hockey", "puck", "reflex", "match", "goal"],
    leaderboardMetric: "wins / score",
    name: "air_hockey",
    obstacles: ["opponent pressure", "fast rebounds", "open goal mistakes"],
    playerGoal: "Score while defending your own goal.",
    reelPrompt: "Fast puck movement, saves, goals, and close match pressure.",
    scoring: "Wins and goals improve ranking.",
    targetAudience: "sports arcade players",
    theme: "3D air hockey",
    title: "Air Hockey 3D",
    videoAssetPath: "src/assets/videos/air_hockey.mp4",
  },
  {
    color: "#1F5E32",
    coreMechanics: ["run", "choose clean lanes", "hit boosts", "finish first"],
    gameId: "game_sprint_rivals",
    gameplaySummary: "A running race where gates become sudden-death checkpoints unless the player is first.",
    hookAngles: ["One bad gap can destroy your lead.", "Can you stay first at every gate?"],
    isPublished: true,
    keywords: ["runner", "race", "boost", "sprint", "rivals"],
    leaderboardMetric: "distance / race progress",
    name: "sprint_rivals",
    obstacles: ["bad gaps", "rivals", "missed boosts", "500m gates"],
    playerGoal: "Stay ahead of rivals and survive each checkpoint.",
    reelPrompt: "Show speed boosts, rivals closing in, and a checkpoint finish.",
    scoring: "Distance and first-place gates push the record.",
    targetAudience: "runner and racing game players",
    theme: "competitive runner",
    title: "Sprint Rivals",
    videoAssetPath: "src/assets/videos/sprint_rivals.mp4",
  },
  {
    color: "#10264A",
    coreMechanics: ["read symbols", "match signals", "clear falling threats"],
    gameId: "game_space_signal",
    gameplaySummary: "A space reaction game where the player clears hostile falling signals before they reach the astronaut.",
    hookAngles: ["Can you decode the signal fast enough?", "The lowest signal is always the emergency."],
    isPublished: true,
    keywords: ["space", "signals", "astronaut", "pattern", "reaction"],
    leaderboardMetric: "waves cleared / score",
    name: "space_signal",
    obstacles: ["falling hostile signals", "stacked enemies", "pattern pressure"],
    playerGoal: "Match the correct signal before enemies reach the astronaut.",
    reelPrompt: "Show symbols falling, fast inputs, and a last-second clear.",
    scoring: "Clean clears and longer waves improve the score.",
    targetAudience: "reaction and pattern puzzle players",
    theme: "space signal defense",
    title: "Space Signal",
    videoAssetPath: "src/assets/videos/space_signal.mp4",
  },
  {
    color: "#1A2235",
    coreMechanics: ["solve arithmetic", "beat timer", "avoid mistakes"],
    gameId: "game_math_quiz",
    gameplaySummary: "A fast math quiz where correct answers and speed build the run.",
    hookAngles: ["This math question looks easy until the timer starts.", "Can you answer faster than the clock?"],
    isPublished: true,
    keywords: ["math", "quiz", "timer", "brain", "challenge"],
    leaderboardMetric: "correct answers / streak",
    name: "math_quiz",
    obstacles: ["timer", "wrong answers", "pressure"],
    playerGoal: "Answer quickly and keep the streak alive.",
    reelPrompt: "Show fast questions, correct taps, timer pressure, and a streak.",
    scoring: "Correct answers and streaks drive the leaderboard.",
    targetAudience: "brain game and quiz players",
    theme: "speed math quiz",
    title: "Math Quiz",
    videoAssetPath: "src/assets/videos/math_quiz.mp4",
  },
  {
    color: "#1A1A1A",
    coreMechanics: ["match colors", "pass obstacles", "time movement"],
    gameId: "game_color_switch",
    gameplaySummary: "A color timing game where the player passes through matching color sections.",
    hookAngles: ["Wrong color, run over.", "Can you time every switch perfectly?"],
    isPublished: true,
    keywords: ["color", "timing", "switch", "arcade", "precision"],
    leaderboardMetric: "points / distance",
    name: "color_switch",
    obstacles: ["wrong colors", "moving arcs", "tight timing"],
    playerGoal: "Pass through matching colors and keep climbing.",
    reelPrompt: "Show color changes, tight passes, and one risky near miss.",
    scoring: "Each clean pass increases the score.",
    targetAudience: "precision arcade players",
    theme: "color timing",
    title: "Color Switch",
    videoAssetPath: "src/assets/videos/color_switch.mp4",
  },
  {
    color: "#5A6B5E",
    coreMechanics: ["move paddle", "keep ball alive", "react to bounces"],
    gameId: "game_paddle_ball",
    gameplaySummary: "A simple paddle reflex game focused on keeping the ball in play.",
    hookAngles: ["Do not let the ball drop.", "This paddle game gets faster than it looks."],
    isPublished: false,
    keywords: ["paddle", "ball", "bounce", "reflex"],
    leaderboardMetric: "rally count / score",
    name: "paddle_ball",
    obstacles: ["fast bounces", "bad angles", "missed returns"],
    playerGoal: "Keep the ball alive as long as possible.",
    reelPrompt: "Show a fast rally and a close save.",
    scoring: "Longer rallies increase the score.",
    targetAudience: "classic arcade players",
    theme: "paddle reflex",
    title: "Paddle Ball",
  },
  {
    color: "#1A1C22",
    coreMechanics: ["eat orbs", "grow longer", "trap rivals", "avoid crashes"],
    gameId: "game_worm_arena",
    gameplaySummary: "A worm arena game where the player grows by collecting orbs and controls space against rivals.",
    hookAngles: ["Can you trap the arena before they trap you?", "Longer worm, bigger risk."],
    isPublished: true,
    keywords: ["worm", "arena", "grow", "orbs", "survival"],
    leaderboardMetric: "length / score",
    name: "worm_arena",
    obstacles: ["rival worms", "head-on crashes", "tight turns"],
    playerGoal: "Grow bigger and survive longer than rivals.",
    reelPrompt: "Show orb collection, growth, a trap, and a crash threat.",
    scoring: "Collecting orbs and surviving increases score.",
    targetAudience: "arena survival players",
    theme: "worm arena survival",
    title: "Worm Arena",
    videoAssetPath: "src/assets/videos/worm_arena.mp4",
  },
  {
    color: "#1A3B66",
    coreMechanics: ["balance penguin", "catch items", "avoid hazards"],
    gameId: "game_penguin_balance",
    gameplaySummary: "An icy balance challenge with a penguin catching useful items while avoiding danger.",
    hookAngles: ["Can this penguin stay balanced?", "One bad catch can ruin the run."],
    isPublished: true,
    keywords: ["penguin", "ice", "balance", "catch", "cute"],
    leaderboardMetric: "score / catches",
    name: "penguin_balance",
    obstacles: ["snowballs", "sharks", "bad hits", "slippery movement"],
    playerGoal: "Keep balance and catch the right items.",
    reelPrompt: "Show the penguin balancing, catching, and narrowly avoiding hazards.",
    scoring: "Good catches increase score while mistakes threaten the run.",
    targetAudience: "cute casual game players",
    theme: "icy balance challenge",
    title: "Penguin Balance",
    videoAssetPath: "src/assets/videos/penguin_balance.mp4",
  },
  {
    color: "#1E7A3A",
    coreMechanics: ["aim direction", "set power", "curve shot", "beat keeper"],
    gameId: "game_penalty_beasts",
    gameplaySummary: "A penalty shootout game with animal athletes, moving defenders, curve shots, and longer-distance goals.",
    hookAngles: ["Can you beat the 13-goal record?", "This penalty shot is harder than it looks."],
    isPublished: true,
    keywords: ["penalty", "soccer", "goals", "keeper", "leaderboard"],
    leaderboardMetric: "goals scored / streak",
    name: "penalty_beasts",
    obstacles: ["keeper saves", "posts", "defenders", "curve timing", "three misses"],
    playerGoal: "Score as many penalties as possible before three misses.",
    reelPrompt: "Show aim, power, curve, a goal, and leaderboard pressure.",
    scoring: "Every goal moves the spot back; three misses end the run.",
    targetAudience: "soccer and quick challenge players",
    theme: "animal penalty shootout",
    title: "Penalty Beasts",
    videoAssetPath: "src/assets/videos/penalty_beasts.mp4",
  },
];
